-d /home/laur/lucru/cn/riscv/rvsoc-site-japan/rvsoc_src_ver053/src/impl/gwsynthesis/project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/laur/lucru/cn/riscv/rvsoc-site-japan/rvsoc_src_ver053/src/rlsoc.cst
-cfg /home/laur/lucru/cn/riscv/rvsoc-site-japan/rvsoc_src_ver053/src/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
