// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vm_topsim.h for the primary calling header

#ifndef VERILATED_VM_TOPSIM_M_CPUMMU_H_
#define VERILATED_VM_TOPSIM_M_CPUMMU_H_  // guard

#include "verilated.h"

class Vm_topsim__Syms;

class Vm_topsim_m_cpummu final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(CLK,0,0);
        VL_IN8(RST_X,0,0);
        VL_OUT8(w_state,3,0);
        VL_OUT8(w_data_we,0,0);
        VL_OUT8(w_data_le,0,0);
        VL_IN8(w_data_busy,3,0);
        VL_OUT8(w_tlb_req,1,0);
        VL_OUT8(w_tlb_busy,0,0);
        VL_IN8(w_plic_we,0,0);
        VL_IN8(w_tx_ready,0,0);
        VL_OUT8(w_dram_we_t,0,0);
        VL_IN8(w_dram_busy,0,0);
        VL_OUT8(w_dram_ctrl,2,0);
        VL_OUT8(w_dram_le,0,0);
        VL_IN8(w_init_done,0,0);
        VL_OUT8(w_reserved,0,0);
        VL_OUT8(w_hart_sc,0,0);
        VL_IN8(w_oh_reserved,0,0);
        VL_IN8(w_oh_sc,0,0);
        VL_OUT8(w_ipi_taken,0,0);
        CData/*0:0*/ w_halt;
        CData/*2:0*/ w_data_ctrl;
        CData/*0:0*/ w_proc_data_we;
        CData/*0:0*/ w_clint_we;
        CData/*0:0*/ w_tlb_flush;
        CData/*0:0*/ w_proc_busy;
        CData/*0:0*/ CORE_RST_X;
        CData/*0:0*/ mmu__DOT__CLK;
        CData/*0:0*/ mmu__DOT__RST_X;
        CData/*0:0*/ mmu__DOT__w_tx_ready;
        CData/*0:0*/ mmu__DOT__w_proc_data_we;
        CData/*0:0*/ mmu__DOT__w_data_we;
        CData/*0:0*/ mmu__DOT__w_data_le;
        CData/*3:0*/ mmu__DOT__w_data_busy;
        CData/*2:0*/ mmu__DOT__w_data_ctrl;
        CData/*1:0*/ mmu__DOT__w_tlb_req;
        CData/*0:0*/ mmu__DOT__w_tlb_flush;
        CData/*0:0*/ mmu__DOT__w_proc_busy;
        CData/*0:0*/ mmu__DOT__w_clint_we;
        CData/*0:0*/ mmu__DOT__w_tlb_busy;
        CData/*0:0*/ mmu__DOT__w_dram_we_t;
        CData/*0:0*/ mmu__DOT__w_dram_busy;
        CData/*2:0*/ mmu__DOT__w_dram_ctrl;
        CData/*0:0*/ mmu__DOT__w_dram_le;
        CData/*0:0*/ mmu__DOT__page_walk_fail;
        CData/*3:0*/ mmu__DOT__r_pw_state;
        CData/*1:0*/ mmu__DOT__r_mc_mode;
        CData/*0:0*/ mmu__DOT__w_mc_we;
        CData/*2:0*/ mmu__DOT__w_mc_ctrl;
        CData/*1:0*/ mmu__DOT__w_mc_aces;
        CData/*0:0*/ mmu__DOT__w_iscode;
        CData/*0:0*/ mmu__DOT__w_isread;
        CData/*0:0*/ mmu__DOT__w_iswrite;
        CData/*2:0*/ mmu__DOT__L1_xwr;
        CData/*0:0*/ mmu__DOT__L1_write;
        CData/*0:0*/ mmu__DOT__L1_success;
        CData/*2:0*/ mmu__DOT__L0_xwr;
        CData/*0:0*/ mmu__DOT__L0_write;
        CData/*0:0*/ mmu__DOT__L0_success;
        CData/*0:0*/ mmu__DOT__w_pte_we;
        CData/*2:0*/ mmu__DOT__r_tlb_use;
        CData/*0:0*/ mmu__DOT__w_tlb_inst_r_oe;
        CData/*0:0*/ mmu__DOT__w_tlb_data_r_oe;
        CData/*0:0*/ mmu__DOT__w_tlb_data_w_oe;
    };
    struct {
        CData/*0:0*/ mmu__DOT__w_use_tlb;
        CData/*0:0*/ mmu__DOT__w_tlb_hit;
        CData/*0:0*/ mmu__DOT__r_dram_was_busy;
        CData/*0:0*/ mmu__DOT__r_dram_took_cmd;
        CData/*0:0*/ mmu__DOT__r_data_was_busy;
        CData/*0:0*/ mmu__DOT__w_tlb_inst_r_we;
        CData/*0:0*/ mmu__DOT__w_tlb_data_r_we;
        CData/*0:0*/ mmu__DOT__w_tlb_data_w_we;
        CData/*0:0*/ mmu__DOT__r_tlb_acs;
        CData/*2:0*/ mmu__DOT__w_mem_ctrl;
        CData/*3:0*/ mmu__DOT__w_dev;
        CData/*3:0*/ mmu__DOT__w_virt;
        CData/*0:0*/ mmu__DOT__w_dram_we;
        CData/*0:0*/ mmu__DOT__w_dram_aces;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__CLK;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__RST_X;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__w_flush;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__w_we;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__w_oe;
        CData/*3:0*/ mmu__DOT__TLB_inst_r__DOT__r_valid;
        CData/*1:0*/ mmu__DOT__TLB_inst_r__DOT__w_ridx;
        CData/*0:0*/ mmu__DOT__TLB_inst_r__DOT__w_tagmatch;
        CData/*1:0*/ mmu__DOT__TLB_inst_r__DOT__w_widx;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__CLK;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__RST_X;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__w_flush;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__w_we;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__w_oe;
        CData/*3:0*/ mmu__DOT__TLB_data_r__DOT__r_valid;
        CData/*1:0*/ mmu__DOT__TLB_data_r__DOT__w_ridx;
        CData/*0:0*/ mmu__DOT__TLB_data_r__DOT__w_tagmatch;
        CData/*1:0*/ mmu__DOT__TLB_data_r__DOT__w_widx;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__CLK;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__RST_X;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__w_flush;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__w_we;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__w_oe;
        CData/*3:0*/ mmu__DOT__TLB_data_w__DOT__r_valid;
        CData/*1:0*/ mmu__DOT__TLB_data_w__DOT__w_ridx;
        CData/*0:0*/ mmu__DOT__TLB_data_w__DOT__w_tagmatch;
        CData/*1:0*/ mmu__DOT__TLB_data_w__DOT__w_widx;
        CData/*0:0*/ p__DOT__CLK;
        CData/*0:0*/ p__DOT__RST_X;
        CData/*0:0*/ p__DOT__w_stall;
        CData/*0:0*/ p__DOT__r_halt;
        CData/*0:0*/ p__DOT__w_data_we;
        CData/*2:0*/ p__DOT__w_data_ctrl;
        CData/*0:0*/ p__DOT__w_clint_we;
        CData/*0:0*/ p__DOT__w_plic_we;
        CData/*0:0*/ p__DOT__w_busy;
        CData/*1:0*/ p__DOT__w_tlb_req;
        CData/*0:0*/ p__DOT__w_tlb_flush;
        CData/*0:0*/ p__DOT__w_init_stage;
        CData/*3:0*/ p__DOT__state;
        CData/*0:0*/ p__DOT__reserved;
        CData/*0:0*/ p__DOT__hart_sc;
        CData/*0:0*/ p__DOT__w_oh_reserved;
        CData/*0:0*/ p__DOT__w_oh_sc;
        CData/*0:0*/ p__DOT__r_ipi_taken;
        CData/*1:0*/ p__DOT__priv;
        CData/*3:0*/ p__DOT__r_was_clint_we;
        CData/*0:0*/ p__DOT__r_cinsn;
        CData/*0:0*/ p__DOT__r_ir16_v;
        CData/*6:0*/ p__DOT__r_opcode;
    };
    struct {
        CData/*4:0*/ p__DOT__r_rd;
        CData/*4:0*/ p__DOT__r_rs1;
        CData/*4:0*/ p__DOT__r_rs2;
        CData/*2:0*/ p__DOT__r_funct3;
        CData/*4:0*/ p__DOT__r_funct5;
        CData/*6:0*/ p__DOT__r_funct7;
        CData/*0:0*/ p__DOT__r_op_AMO_SC;
        CData/*0:0*/ p__DOT__r_op_AMO_LR;
        CData/*0:0*/ p__DOT__r_op_LOAD;
        CData/*0:0*/ p__DOT__r_op_STORE;
        CData/*0:0*/ p__DOT__r_op_AMO;
        CData/*0:0*/ p__DOT__r_op_SYS;
        CData/*0:0*/ p__DOT__r_op_ECALL;
        CData/*0:0*/ p__DOT__r_op_SRET;
        CData/*0:0*/ p__DOT__r_op_MRET;
        CData/*0:0*/ p__DOT__r_op_CSR_MSTA;
        CData/*0:0*/ p__DOT__r_op_CSR_SSTA;
        CData/*6:0*/ p__DOT__r_alu_f7;
        CData/*0:0*/ p__DOT__r_tkn;
        CData/*0:0*/ p__DOT__r_if_done;
        CData/*1:0*/ p__DOT__r_if_state;
        CData/*0:0*/ p__DOT__w_wb_r_enable;
        CData/*3:0*/ p__DOT__w_state;
        CData/*0:0*/ p__DOT__r_init_stage;
        CData/*0:0*/ p__DOT__w_nalign4;
        CData/*0:0*/ p__DOT__w_usestate;
        CData/*1:0*/ p__DOT__w_if_state;
        CData/*0:0*/ p__DOT__w_cinsn;
        CData/*0:0*/ p__DOT__w_nop;
        CData/*4:0*/ p__DOT__w_rs1;
        CData/*4:0*/ p__DOT__w_rs2;
        CData/*0:0*/ p__DOT__w_regfile_we;
        CData/*0:0*/ p__DOT__w_op_priv;
        CData/*0:0*/ p__DOT__w_op_csr;
        CData/*0:0*/ p__DOT__w_alu_b_rslt;
        CData/*0:0*/ p__DOT__w_ex1;
        CData/*0:0*/ p__DOT__w_ex1_busy;
        CData/*2:0*/ p__DOT__r_data_ctrl;
        CData/*1:0*/ p__DOT__r_priv_t;
        CData/*0:0*/ p__DOT__w_executing_wfi;
        CData/*0:0*/ p__DOT__w_exit_wfi;
        CData/*0:0*/ p__DOT__w_csr_we;
        CData/*0:0*/ p__DOT__w_take_int;
        CData/*0:0*/ p__DOT__r_tlb_flush;
        CData/*0:0*/ p__DOT__w_com;
        CData/*2:0*/ p__DOT__r_com;
        CData/*0:0*/ p__DOT__w_d_we_t;
        CData/*0:0*/ p__DOT__w_d_en_t;
        CData/*0:0*/ p__DOT__r_data_we;
        CData/*0:0*/ p__DOT__r_data_en;
        CData/*1:0*/ p__DOT__r_tlb_req;
        CData/*0:0*/ p__DOT____VdfgTmp_h8573667a__0;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c0_rs1;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c0_rs2;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c0_rd;
        CData/*1:0*/ p__DOT__decomp0__DOT__w_c1_funct1;
        CData/*2:0*/ p__DOT__decomp0__DOT__w_c1_funct2;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c1_rs1;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c1_rs2;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c1_rd;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c1_shamt;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c2_rs2;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c2_rd;
        CData/*4:0*/ p__DOT__decomp0__DOT__w_c2_shamt;
    };
    struct {
        CData/*6:0*/ p__DOT__imm_gen0__DOT__opcode;
        CData/*0:0*/ p__DOT__regs__DOT__CLK;
        CData/*4:0*/ p__DOT__regs__DOT__w_rs1;
        CData/*4:0*/ p__DOT__regs__DOT__w_rs2;
        CData/*0:0*/ p__DOT__regs__DOT__w_we;
        CData/*4:0*/ p__DOT__regs__DOT__rd;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__CLK;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__RST_X;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_le;
        CData/*2:0*/ p__DOT__ALU_IM__DOT__w_funct3;
        CData/*6:0*/ p__DOT__ALU_IM__DOT__w_funct7;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_busy;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__r_div_first;
        CData/*4:0*/ p__DOT__ALU_IM__DOT__w_shamt;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_divunit_busy;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_div_req;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_div_init;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__w_div_signed;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__CLK;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__RST_X;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_init;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_signed;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_busy;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_sign_dividend;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_sign_divisor;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__CLK;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__RST_X;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_init;
        CData/*0:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_busy;
        CData/*5:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_count;
        CData/*2:0*/ p__DOT__ALU_B__DOT__w_funct3;
        CData/*0:0*/ p__DOT__ALU_B__DOT__r_rslt;
        CData/*2:0*/ p__DOT__ALU_C__DOT__w_funct3;
        CData/*4:0*/ p__DOT__ALU_A__DOT__w_funct5;
        SData/*15:0*/ p__DOT__r_ir16;
        SData/*11:0*/ p__DOT__r_funct12;
        SData/*15:0*/ p__DOT__r_if_irl;
        SData/*11:0*/ p__DOT__w_csr_addr;
        VL_IN(w_hart_id,31,0);
        VL_IN(w_grant,31,0);
        VL_IN(w_ipi,31,0);
        VL_OUT(w_core_ir,31,0);
        VL_OUT(w_mem_paddr,31,0);
        VL_OUT(w_data_wdata,31,0);
        VL_IN(w_data_data,31,0);
        VL_OUT(w_mip,31,0);
        VL_IN(w_wmip,31,0);
        VL_OUT(w_dram_addr,31,0);
        VL_OUT(w_dram_wdata,31,0);
        VL_IN(w_dram_odata,31,0);
        VL_OUT(w_pc,31,0);
        VL_OUT(w_ir,31,0);
        VL_OUT(w_pc_stip,31,0);
        VL_OUT(w_load_res,31,0);
        VL_IN(w_oh_load_res,31,0);
        VL_IN(w_oh_pc,31,0);
        IData/*31:0*/ w_insn_data;
        IData/*31:0*/ w_insn_addr;
        IData/*31:0*/ w_data_addr;
        IData/*31:0*/ w_priv;
        IData/*31:0*/ w_satp;
        IData/*31:0*/ w_mstatus;
        IData/*31:0*/ w_pagefault;
        IData/*31:0*/ mmu__DOT__w_hart_id;
    };
    struct {
        IData/*31:0*/ mmu__DOT__w_grant;
        IData/*31:0*/ mmu__DOT__w_pc;
        IData/*31:0*/ mmu__DOT__w_ir;
        IData/*31:0*/ mmu__DOT__w_insn_addr;
        IData/*31:0*/ mmu__DOT__w_data_addr;
        IData/*31:0*/ mmu__DOT__w_data_wdata;
        IData/*31:0*/ mmu__DOT__w_insn_data;
        IData/*31:0*/ mmu__DOT__w_priv;
        IData/*31:0*/ mmu__DOT__w_satp;
        IData/*31:0*/ mmu__DOT__w_mstatus;
        IData/*31:0*/ mmu__DOT__w_pagefault;
        IData/*31:0*/ mmu__DOT__w_mem_paddr;
        IData/*31:0*/ mmu__DOT__w_dram_addr;
        IData/*31:0*/ mmu__DOT__w_dram_wdata;
        IData/*31:0*/ mmu__DOT__w_dram_odata;
        IData/*31:0*/ mmu__DOT__physical_addr;
        IData/*31:0*/ mmu__DOT__L1_pte;
        IData/*31:0*/ mmu__DOT__L0_pte;
        IData/*31:0*/ mmu__DOT__w_mc_addr;
        IData/*31:0*/ mmu__DOT__w_mc_wdata;
        IData/*31:0*/ mmu__DOT__w_mem_wdata;
        IData/*31:0*/ mmu__DOT__v_addr;
        IData/*31:0*/ mmu__DOT__vpn1;
        IData/*31:0*/ mmu__DOT__L1_pte_addr;
        IData/*31:0*/ mmu__DOT__L1_paddr;
        IData/*31:0*/ mmu__DOT__L1_p_addr;
        IData/*31:0*/ mmu__DOT__vpn0;
        IData/*31:0*/ mmu__DOT__L0_pte_addr;
        IData/*31:0*/ mmu__DOT__L0_paddr;
        IData/*31:0*/ mmu__DOT__L0_p_addr;
        IData/*31:0*/ mmu__DOT__L1_pte_write;
        IData/*31:0*/ mmu__DOT__L0_pte_write;
        IData/*31:0*/ mmu__DOT__w_pte_waddr;
        IData/*31:0*/ mmu__DOT__w_pte_wdata;
        IData/*31:0*/ mmu__DOT__r_tlb_addr;
        IData/*21:0*/ mmu__DOT__w_tlb_inst_r_addr;
        IData/*21:0*/ mmu__DOT__w_tlb_data_r_addr;
        IData/*21:0*/ mmu__DOT__w_tlb_data_w_addr;
        IData/*21:0*/ mmu__DOT__w_tlb_wdata;
        IData/*31:0*/ mmu__DOT__r_tlb_pte_addr;
        IData/*31:0*/ mmu__DOT__w_insn_paddr;
        IData/*27:0*/ mmu__DOT__w_offset;
        IData/*19:0*/ mmu__DOT__TLB_inst_r__DOT__w_waddr;
        IData/*19:0*/ mmu__DOT__TLB_inst_r__DOT__w_raddr;
        IData/*21:0*/ mmu__DOT__TLB_inst_r__DOT__w_idata;
        IData/*21:0*/ mmu__DOT__TLB_inst_r__DOT__w_odata;
        IData/*31:0*/ mmu__DOT__TLB_inst_r__DOT__i;
        IData/*17:0*/ mmu__DOT__TLB_inst_r__DOT__w_rtag;
        IData/*17:0*/ mmu__DOT__TLB_inst_r__DOT__w_wtag;
        IData/*19:0*/ mmu__DOT__TLB_data_r__DOT__w_waddr;
        IData/*19:0*/ mmu__DOT__TLB_data_r__DOT__w_raddr;
        IData/*21:0*/ mmu__DOT__TLB_data_r__DOT__w_idata;
        IData/*21:0*/ mmu__DOT__TLB_data_r__DOT__w_odata;
        IData/*31:0*/ mmu__DOT__TLB_data_r__DOT__i;
        IData/*17:0*/ mmu__DOT__TLB_data_r__DOT__w_rtag;
        IData/*17:0*/ mmu__DOT__TLB_data_r__DOT__w_wtag;
        IData/*19:0*/ mmu__DOT__TLB_data_w__DOT__w_waddr;
        IData/*19:0*/ mmu__DOT__TLB_data_w__DOT__w_raddr;
        IData/*21:0*/ mmu__DOT__TLB_data_w__DOT__w_idata;
        IData/*21:0*/ mmu__DOT__TLB_data_w__DOT__w_odata;
        IData/*31:0*/ mmu__DOT__TLB_data_w__DOT__i;
        IData/*17:0*/ mmu__DOT__TLB_data_w__DOT__w_rtag;
        IData/*17:0*/ mmu__DOT__TLB_data_w__DOT__w_wtag;
        IData/*31:0*/ p__DOT__w_hart_id;
    };
    struct {
        IData/*31:0*/ p__DOT__w_ipi;
        IData/*31:0*/ p__DOT__w_insn_addr;
        IData/*31:0*/ p__DOT__w_data_addr;
        IData/*31:0*/ p__DOT__w_insn_data;
        IData/*31:0*/ p__DOT__w_data_data;
        IData/*31:0*/ p__DOT__w_data_wdata;
        IData/*31:0*/ p__DOT__w_priv;
        IData/*31:0*/ p__DOT__w_satp;
        IData/*31:0*/ p__DOT__w_mstatus;
        IData/*31:0*/ p__DOT__w_mip;
        IData/*31:0*/ p__DOT__w_wmip;
        IData/*31:0*/ p__DOT__w_pagefault;
        IData/*31:0*/ p__DOT__w_core_pc;
        IData/*31:0*/ p__DOT__w_core_ir;
        IData/*31:0*/ p__DOT__w_core_odata;
        IData/*31:0*/ p__DOT__pc;
        IData/*31:0*/ p__DOT__r_ir;
        IData/*31:0*/ p__DOT__pc_stip;
        IData/*31:0*/ p__DOT__load_res;
        IData/*31:0*/ p__DOT__w_oh_load_res;
        IData/*31:0*/ p__DOT__w_oh_pc;
        IData/*31:0*/ p__DOT__w_grant;
        IData/*31:0*/ p__DOT__mstatus;
        IData/*31:0*/ p__DOT__mtvec;
        IData/*31:0*/ p__DOT__mscratch;
        IData/*31:0*/ p__DOT__mepc;
        IData/*31:0*/ p__DOT__mcause;
        IData/*31:0*/ p__DOT__mtval;
        IData/*31:0*/ p__DOT__mhartid;
        IData/*31:0*/ p__DOT__misa;
        IData/*31:0*/ p__DOT__mie;
        IData/*31:0*/ p__DOT__mip;
        IData/*31:0*/ p__DOT__medeleg;
        IData/*31:0*/ p__DOT__mideleg;
        IData/*31:0*/ p__DOT__mcounteren;
        IData/*31:0*/ p__DOT__stvec;
        IData/*31:0*/ p__DOT__sscratch;
        IData/*31:0*/ p__DOT__sepc;
        IData/*31:0*/ p__DOT__scause;
        IData/*31:0*/ p__DOT__stval;
        IData/*31:0*/ p__DOT__satp;
        IData/*31:0*/ p__DOT__scounteren;
        IData/*31:0*/ p__DOT__pending_tval;
        IData/*31:0*/ p__DOT__pending_exception;
        IData/*31:0*/ p__DOT__r_cpc;
        IData/*31:0*/ p__DOT__r_ir_org;
        IData/*31:0*/ p__DOT__r_imm;
        IData/*31:0*/ p__DOT__r_rrs1;
        IData/*31:0*/ p__DOT__r_rrs2;
        IData/*31:0*/ p__DOT__r_rcsr;
        IData/*31:0*/ p__DOT__r_alu_in2;
        IData/*31:0*/ p__DOT__r_jmp_pc;
        IData/*31:0*/ p__DOT__r_mem_addr;
        IData/*31:0*/ p__DOT__r_wb_data;
        IData/*31:0*/ p__DOT__r_wb_data_csr;
        IData/*31:0*/ p__DOT__r_mem_rdata;
        IData/*31:0*/ p__DOT__r_atom_wdata;
        IData/*31:0*/ p__DOT__r_rcsr_t;
        IData/*31:0*/ p__DOT__irq_num;
        IData/*31:0*/ p__DOT__w_wb_r_data;
        IData/*31:0*/ p__DOT__w_interrupt_mask;
        IData/*31:0*/ p__DOT__w_irq_t;
        IData/*31:0*/ p__DOT__w_vadr1;
        IData/*31:0*/ p__DOT__w_vadr2;
    };
    struct {
        IData/*31:0*/ p__DOT__r_insn_addr;
        IData/*31:0*/ p__DOT__w_ir_org;
        IData/*31:0*/ p__DOT__w_ir_t;
        IData/*31:0*/ p__DOT__w_ir;
        IData/*31:0*/ p__DOT__w_imm;
        IData/*31:0*/ p__DOT__w_rrs1;
        IData/*31:0*/ p__DOT__w_rrs2;
        IData/*31:0*/ p__DOT__w_sin1;
        IData/*31:0*/ p__DOT__w_sin2;
        IData/*31:0*/ p__DOT__w_mem_addr;
        IData/*31:0*/ p__DOT__w_alu_im_rslt;
        IData/*31:0*/ p__DOT__w_alu_c_rslt;
        IData/*31:0*/ p__DOT__w_mem_rdata;
        IData/*31:0*/ p__DOT__r_lrpc;
        IData/*31:0*/ p__DOT__r_lrmtime;
        IData/*31:0*/ p__DOT__w_alu_a_rslt;
        IData/*31:0*/ p__DOT__r_data_wdata;
        IData/*31:0*/ p__DOT__r_mstatus_t;
        IData/*31:0*/ p__DOT__w_mstatus_nxt;
        IData/*31:0*/ p__DOT__pending_interrupts;
        IData/*31:0*/ p__DOT__enable_interrupts;
        IData/*31:0*/ p__DOT__cause;
        IData/*31:0*/ p__DOT__w_deleg;
        IData/*31:0*/ p__DOT__w_sstatus_t;
        IData/*31:0*/ p__DOT__w_mstatus_t;
        IData/*31:0*/ p__DOT__w_sstatus;
        IData/*31:0*/ p__DOT__w_sstatus_t1;
        IData/*31:0*/ p__DOT__w_sstatus_t2;
        IData/*31:0*/ p__DOT__w_sstatus_t3;
        IData/*31:0*/ p__DOT__w_mstatus_t1;
        IData/*31:0*/ p__DOT__w_mstatus_t2;
        IData/*31:0*/ p__DOT__w_mstatus_t3;
        IData/*31:0*/ p__DOT__laurpc;
        IData/*31:0*/ p__DOT__f;
        IData/*31:0*/ p__DOT__closed;
        IData/*31:0*/ p__DOT__r_ipi_max_displays;
        IData/*31:0*/ p__DOT__rim;
        IData/*31:0*/ p__DOT__w_data_t;
        IData/*31:0*/ p__DOT__w_mod;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_ic;
        IData/*31:0*/ p__DOT__decomp0__DOT__r_iw;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c0_uimm1;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c0_uimm2;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c0_nzuimm;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c1_nzimm;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c1_imm1;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c1_imm2;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c1_imm3;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c1_imm4;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c2_uimm1;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c2_uimm2;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c2_uimm3;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c2_uimm4;
        IData/*31:0*/ p__DOT__decomp0__DOT__w_c2_nzuimm;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__w_inst;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__r_imm;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_I;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_S;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_B;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_U;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_J;
        IData/*31:0*/ p__DOT__imm_gen0__DOT__imm_C;
        IData/*31:0*/ p__DOT__regs__DOT__w_rdata1;
        IData/*31:0*/ p__DOT__regs__DOT__w_rdata2;
    };
    struct {
        IData/*31:0*/ p__DOT__regs__DOT__w_wdata;
        IData/*31:0*/ p__DOT__regs__DOT__w_hart_id;
        IData/*31:0*/ p__DOT__regs__DOT__i;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__w_in1;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__w_in2;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__r_rslt;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__w_sin1;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__w_sin2;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_dividend;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_divisor;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_dividend;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_divisor;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_dividend;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_divisor;
        IData/*31:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_divisor;
        IData/*31:0*/ p__DOT__ALU_B__DOT__w_in1;
        IData/*31:0*/ p__DOT__ALU_B__DOT__w_in2;
        IData/*31:0*/ p__DOT__ALU_B__DOT__w_sin1;
        IData/*31:0*/ p__DOT__ALU_B__DOT__w_sin2;
        IData/*31:0*/ p__DOT__ALU_C__DOT__w_rcsr;
        IData/*31:0*/ p__DOT__ALU_C__DOT__w_rrs1;
        IData/*31:0*/ p__DOT__ALU_C__DOT__w_imm;
        IData/*31:0*/ p__DOT__ALU_C__DOT__r_rslt;
        IData/*31:0*/ p__DOT__ALU_A__DOT__w_in1;
        IData/*31:0*/ p__DOT__ALU_A__DOT__w_in2;
        IData/*31:0*/ p__DOT__ALU_A__DOT__r_rslt;
        IData/*31:0*/ p__DOT__ALU_A__DOT__w_sin1;
        IData/*31:0*/ p__DOT__ALU_A__DOT__w_sin2;
        VL_IN64(w_mtime,63,0);
        QData/*63:0*/ w_mtimecmp;
        QData/*63:0*/ w_wmtimecmp;
        QData/*63:0*/ mmu__DOT__w_mtimecmp;
        QData/*63:0*/ mmu__DOT__w_wmtimecmp;
        QData/*63:0*/ p__DOT__w_mtime;
        QData/*63:0*/ p__DOT__w_mtimecmp;
        QData/*63:0*/ p__DOT__w_wmtimecmp;
        QData/*63:0*/ p__DOT__mtimecmp;
        QData/*63:0*/ p__DOT__e_icount;
        QData/*63:0*/ p__DOT__w_mul_SS;
        QData/*63:0*/ p__DOT__w_mul_SU;
        QData/*63:0*/ p__DOT__w_mul_UU;
        QData/*63:0*/ p__DOT__r_mul_SS;
        QData/*63:0*/ p__DOT__r_mul_SU;
        QData/*63:0*/ p__DOT__r_mul_UU;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__w_mul_SS;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__w_mul_SU;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__w_mul_UU;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__w_divunit_rslt;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__w_div_rslt;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_rslt;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__w_uint_rslt;
        QData/*63:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__r_rslt;
        QData/*32:0*/ p__DOT__ALU_IM__DOT__divunit__DOT__divcore__DOT__w_differ;
        VlUnpacked<QData/*39:0*/, 4> mmu__DOT__TLB_inst_r__DOT__mem;
        VlUnpacked<QData/*39:0*/, 4> mmu__DOT__TLB_data_r__DOT__mem;
        VlUnpacked<QData/*39:0*/, 4> mmu__DOT__TLB_data_w__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> p__DOT__regs__DOT__mem;
    };

    // INTERNAL VARIABLES
    Vm_topsim__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ mmu__DOT__TLB_inst_r__DOT__ADDR_WIDTH = 0x00000014U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_inst_r__DOT__D_WIDTH = 0x00000016U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_inst_r__DOT__ENTRY = 4U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_r__DOT__ADDR_WIDTH = 0x00000014U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_r__DOT__D_WIDTH = 0x00000016U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_r__DOT__ENTRY = 4U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_w__DOT__ADDR_WIDTH = 0x00000014U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_w__DOT__D_WIDTH = 0x00000016U;
    static constexpr IData/*31:0*/ mmu__DOT__TLB_data_w__DOT__ENTRY = 4U;

    // CONSTRUCTORS
    Vm_topsim_m_cpummu(Vm_topsim__Syms* symsp, const char* name);
    ~Vm_topsim_m_cpummu();
    VL_UNCOPYABLE(Vm_topsim_m_cpummu);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
